apiVersion: v2
name: direktiv
namespace: direktiv-services-direktiv
description: direktiv Helm chart for Kubernetes
type: application
version: 0.5.10
appVersion: "0.5.10"

dependencies:
- name: direktiv
  chart: direktiv/direktiv
  version: 0.5.10
  repository: https://charts.direktiv.io
  condition: deployChart.enabled
  values:
    - ../demo-direktiv-values.yaml
