helmCharts:
- name: keptn
  namespace: keptn
  version: 0.12.0
  repo: https://storage.googleapis.com/keptn-installer
  releaseName: keptn
  includeCRDs: true
  valuesInline: 
    control-plane:
      enabled: true
      apiGatewayNginx:
        type: ClusterIP
        port: 80
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-demo-aws
        host: "keptn.bradmccoy.io"
        path: /
        pathType: Prefix
        tls:
          - secretName: keptn-tls-certificate
            hosts:
              - keptn.bradmccoy.io
        
    continuous-delivery:
      enabled: true 

- name: helm-service
  namespace: ci-cd
  version: 0.12.0
  repo: https://storage.googleapis.com/keptn-installer
  releaseName: helm-service
  includeCRDs: true

- name: jmeter-service
  namespace: ci-cd
  version: 0.12.0
  repo: https://storage.googleapis.com/keptn-installer
  releaseName: jmeter-service
  includeCRDs: true
