control-plane:
  enabled: true
  apiGatewayNginx:
    type: ClusterIP
    port: 80
  
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: "false"
    host: "keptn.bradmccoy.io"
    path: /
    pathType: Prefix

continuous-delivery:
  enabled: true  
