helmCharts:
- name: loki
  namespace: observability
  version: 2.8.4
  repo: https://grafana.github.io/helm-charts 
  releaseName: grafana/loki
  includeCRDs: false
  valuesInline: 
    fluent-bit:
    enabled: true

    loki:
      config:
        table_manager:
          retention_deletes_enabled: true
          retention_period: 720h
        persistence:
          enabled: true
          size: 10Gi

