apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
- trust-anchor-sealed.yaml
- trust-issuer.yaml
patchesStrategicMerge:
- trust-anchor-patch.yaml