apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- namespace.yaml
- trust-anchor-sealed.yaml
- trust-issuer.yaml
- ../../base
patchesStrategicMerge:
- trust-anchor-patch.yaml