apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: web-ingress-auth
  namespace: linkerd
spec:
  encryptedData:
    auth: AgCOlhVwHcgKCpVsT3DA+IUIB8yqftr4mDzqffzMgHNSfpno8luao3bcRzxNzZlJni1tbN0eJNmAJJl+BKQaOlHSJKpQvN2HiJm4MhPaiKDvwezhDImLqNJ1KPzXT+Ko7z+ZUEaxPSVpODJWO7U8Z3lTD70+eAd5E5ikf6dLcd6yf5g89SgdjSPejjLxvPdcCsREFLSwwTRXJ+kL1sOsMsf94O1H3cOrg1920+kJazUtDvnD/9cV0gogzdHNyQD/Pqkizu0XGf4EWi2v4eYw0i+RIT95dI/VizYw5YEi2HDvmFIuKfFxs3+WLDMKPsdsopz19DgEGhPTcGPKt8YXroklFb3LlP+GSyuf6pJUun0VjYgH9AaWSREc0NqO51qVjj30wMF+svUhV7rR4v8GfrEy8onOAtdvpgStul9coAL5kjX2nT8lQXkWrFfaxqB2rNAYIdcKLznCG1lGNvD+0cDPG/BHjgUGW6u5a+tIXuGcE2nejLp8m4hzxLJTB8/UfVJO8FpdWXOPqH1iyrTyzHlRMN0VVyRSTdSjbhI0jNqwrEx7QjFjm/8J0GSyNITY9uS8ChFiR4JnyNB8LajhZTy68aSm8H6+QkITOX3jNHoh5dKuuax9C/vkEQeTG0nCdKcSPr6kKSTbtnMYZbuoLdwXKG+XTAxmDfm2uQKr3TBGpddfbMdIeQZPi1yiTXwOrUk8BTMTBRhELT7HDvHgoQvegpbzfPMY+lz0U+NsvxVam6XO58AQb6XbcQtq
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        environment: demo
        folder: service-mesh
        subFolder: linkerd
      name: web-ingress-auth
      namespace: linkerd

