apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: web-ingress-auth
  namespace: linkerd
spec:
  encryptedData:
    auth: AgBuJ8o/VbCHmHV/358589aiT8u38pVYKdMkcBD3x0EdRrcZIsC0iWo9N2A/oKiQYAzUmXuy7DocMpWhb1uL/Fr90wFFdYpwTFElKa2/T6dV2r3NZl4G0m8ZWJxemoPFl7SHYSrrZU8QXjmWSgzMRyBqfhWZ+P7M5ANhp4u9kjnB5WU3sKt0seWlj7EQLF5yApmEpC2zu49DDSuOP1D6F8IWCEdGi6Dl3qjMB2uxsmGEt5dyP+DVIiMwabD/Ift2ZaOOKwjyan07UERrY3204yx5mmXS7dH5MkKyks3lMDi5Izno5iENCeGnihceTSs5eRbcqG40OAdS/cUj3khl01Olg5UsW3KkXR3rVTNqvM0hL1lci5RcZYRGs6W07LVg3vZs6akcrDtYLWq7nvItXA/0Nfzsi5DZGF+Hg4PRK1OVCXeTkbHw5dBc9m8qFFtNHyiJ694nmb+X/uwJITng7NgOMiQ9EaZUkXT5Xqini4rCJw1GWBZdwTq7xvPvnR0fWF2ozdLPE1HF+xObi95T08e85uIVZifvj9jKAR7V5MAnedmltrgGe4n62NKFkgR1LKFov0Fth58UoepNdT+dIgsjQqBhlg/MCrHhkqNDIJkCGUXEWrvXLSGoaMJ/GjAUmJgI7Ft8TmEAwBTI2r/9hHMNbPgrJcAMM5JQdlxG8E4utTOXue2w6kVwdo0JUzS+33eHHdtzgOioT8WIqYbrNK8jXs36jWZVkiAMyKAyILQeUZRbH+xSp1+0sN6C
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        environment: demo
        folder: service-mesh
        subFolder: linkerd
      name: web-ingress-auth
      namespace: linkerd

