apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-dns-creds
  namespace: dns-infra
spec:
  encryptedData:
    AWS_ACCESS_KEY: AgAA76rRuwQO3x6nUq3HRpmRERCeCP1jzowv3kThKXpq6VdTWzr2rzsHwbQ5F85qsWIYIwcfuSp6Gx4f8V6lYuvA8Rv0pWVJH0R9XsCW8LwXlGSTmxc+pfQQP2cXeBADC7Wz7O4oTltAvxHPyhNdD+voZZZpEYDOMa9blsvrUjbJMNHHT8i5mo5jqr/aO0IPUdWDkjlYfRkVEX5h8IYPC8HC4OyINjQmR5CEMV8SBste+SWH3yq/EiUFLd1+He8uMApHyJ+eJVkmeTKBfnUO+G0fm4InFcAu7gUCuDZnaaRBIf8YxrGzZ/L/LkjWapVh87GZq5ani1LdCKGYWYuV7atu+DTLHAsw5ch2Wb9ycfl8Bdn/cUS88P6dXbIEf771S8YHCgNjLmSnV0dEmqwrQA/GO6fF2HaSWeYQbTaHu6QmP8ifr0kuaw1H/qfrKA59zNCPlsS8l2D7GGAQJLJ+2DMP2oncPMfbx4fxLb7e1MNWD4/VhHu9dRrImF6ei4aRZ2vFuqWiOjvVA7UBe/kZ/Mk90frHmZazYLzSXBkDiUw+75BIxDE1uwVPWCXGMY+xIQqw+1k74bWbKsu+S9IGj15llrAJSOyRlj2ku4yzMMnpPkzENvjtDfq6cuH+UtFkUsqu9+OPat7yV1lZaMZsgpU1btsvCQwrlMO6BZjLRrhGAU3lijgEiTnA1r4/CDLGljfz/pizFHGqeIA3pmpgXQWfS9ggrQ==
    AWS_SECRET_ACCESS_KEY: AgAMB19z/LE9WIS3INPzzVqfCFkx5Shz0KH3RhCGUxhzzFbc1ykzKwC8gOK5yAXoK8ZnVp/NhBfAYRCKzqWmIRJxbP2LosEavt55fdyzFnaqiSxaDcWxmy2pCmcI0e15d6ZWpOsQ9+haOzd0LEaAle2rX1bwt/Z8LtJKCMRk0BzzsjnlZFCLxMEMpB2/jMX/LUPCeekRqaFNgfHHU7up0OS9T+qGyG6DF3bzPUquDBMkqBJ9LF+o7MhMUTyHhd6JYd7pyJD2o+EkxjYh8gB3J1d83LyV15iU54uOotlqxt+VDK3WRtxAE4alTLO5dI2iEz28q6HZaoeYCs2S9IoeWv3ZhiV+edI+x3DTqXs9kazjeJoNCVto4L4XE+/UAwhk3hvFhKMMlicgD6TM5e+PN48v8wFwfe10BT7joHojeZmLeZwsSMx6vgzfeO/WPMl9yzoExIXoe6/RwdVnms+501jwTPv2d2iwdVqn3OaNbiSDdzY2Kp2Jhkn8f+QU1+HNV+bNm0Zpj2D8nGumhtBhCxmnW6r4sptOQztJJMPdiuCf132kpLPH4WBwuqAPaJNIFNbdswrRHGeQ4o7MwZziP1Qq6zbaHaxX8NZt2DY6LCRC6NATeCB56H2Kk3riSCV3/MZkCaZ22i/Usoir4Ln3K426PICHvA+zegdjD50UCDbZLA3i2AccOnWf+3Gmf1IdEw3gywKZbQEDkfatt8VQCnZg6Q71XeRDLppRQ3qdbXTq8aM8aI8zvQKp
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-dns-creds
      namespace: dns-infra
    type: Opaque

