apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-dns-creds
  namespace: dns-infra
spec:
  encryptedData:
    AWS_ACCESS_KEY: AgBX3caj8r5lodSUKxTi3k+Skui3umavEkEEicVY6Ybzn30F8MzXH8vYoRm+Bw4wj0UcTgpfwvfar6tQDfTSfPaEgW+f49uA96bpstERWqzV/YQ3FbTCKxyN4Rni+1ka7SRZddBz1RalpQhhLoqwivFrRMnNwxSFSJNf6EdhP80kRs8jjEjgqJ1oS0hCHO42bCDcKaxHFhk5WCIfhW6jFA+PY2fQ+0FJnWRT+ZP93h/5G2loDh0mh8dzoMMOtYSToGUgMTOYYmZgeblbvISiEOh0gv3YbKPk4tlM6oEtZopKnkwmoZ/ViQj88nURRHLw16N7J6YxkO0GhG3g5yBplR2q/GkgCp49z+ZowfMeEjz+Z1dX6+c7K89aHOwEHbQwEQzpQCIv7WRS0ZL03CC9+C5BnxyyDKpDfc3Y2gaMyDNjgx5M/p0MWgNcR54Dg2HAsf/0XC1KuaOe0Wi+xnd7gLanz0QvYh6KjTQXv1fF+DnKyL4UUg+U3Ylj7YBI+Fw3fcWY7FS7eZAE5rYSGGs9J9VNNq6nxMeJ9i1K5PtNzUNIeO6LfamC33043oMkA/uAFqS+AhfFDGKf/oLueD8BXLgusr9MHqm24dowWa9Ryj3+6pXBQEWqQGgDNR1CdRAztWOhjr2BMbMPswUJI6RSFNRWlSgXpxE8T5zd9hgtV6SBBjXR1yqwuwMP4zrh2z5LBGrQlNb2bJ60YI9alhoZqD7/HDPACw==
    AWS_SECRET_ACCESS_KEY: AgBTI4NQXNwjLGtPVfOxmcIZlF4fsaYdElHAsqg7fRVSpoKCCRATKus1/ZXJwfZYcMEG1aP4ubrs0kTQrNsItNabO272KF/fBdLrVo/gcR0Nk0n9DseFKAZoDOLK7z6JjOpYoebPcaMaXnp8v4ebA3s/1ERwlGY862/3bx/yAwPdncQJk23UNq8Id4umgMGYCTDabWgJaujrz5snhFOqGeUMEKANgUF0VGbGooUQiLXwlsiIMQYz/Ng/DfT98x+pu6qwrJ1Kjlo+1aDq5Q1K7/2rufuagyG0stUqxT7xW83+AbUGSSf6fv2jeifFYeM9+nVqmrnEyyUUCHscsLYiwcR+r7chR56GSVWejouUQa7fW6zZxF3rrpJNogirASEfF6RDRu/ABtDYjVATykLSjTg8OYI7e10iPzjcNynmWVwkWwu+qfz2hMG1ml65Zxw5CfR4KdI2NKgykVAj9xHhg3gECwsDQlxcU/c20f2MTV1wsJd/CaWpsM70R0+MbNgtjbPW0J6dBSz5t6TuarBvOlzsdSIYEwYFlZPOjgxKkdENrs1ld2PpgYlOzwdANntT8FYEraolc4vCE4b0tFekh/nNnrpIhxR4OXUrQkRjAb5wYlDtXClAGWZV/GnInCjQ6HMOHuua+NSaP4HnouOH7Rv/OKkORfjndWCLv3PsoIqKMo7RHdLlv16qjeaVwZql4CRbFiN5JqGlAmrUt/212j/VWPTWFoIVdZXQfUxM1zQwiAYW9AIjrG4Z
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-dns-creds
      namespace: dns-infra
    type: Opaque

