apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-dns-creds
  namespace: dns-infra
spec:
  encryptedData:
    AWS_ACCESS_KEY: AgBxI6pml9gpbzeuFNpnTDFxym9a6i4cBdZ3rX6sZl4VURVtZ6H4vT5K00VTCcguB1sJ/uEG1qEPOSnaPWZ4+SeeKEE4ySchgDIiUtLRl3ZtpJXTVMS2kqukCDhZU2vp4GjNk9bkSTAJaTztvKc6Fkz7uClezryaFx74m7xhGz2BNOs2dnvdzV+QOgFR1Lew8aPGJFy5BpBGat/c30+DiuRS6RsXNsQ1dgJXZ38q5/RRrQsWEqQS0+LNP6TIHqzck5vc66OWuFMhLpwdxjDmVy8QjejUZjANQ6ugy3VNJ1fkAOo7EebT58tKv0Uly0GYS7n2dF1DtUZRNYrbLTLkgsLbE8jr11Ayw8iVTp3lBTiW8MWWABBvzI8EjrStu4t6Cb+yCZyK1h7ynaFBwLR/G9ATFjK05kJ8PhP56687tKBDdsIyad5XsfoyTBfLFWQFktreuUu9/D3xGSs4CrtwAmLoWgTPlqUc7j7R/pSXmXvbAjzZcYOyddlqjbmevWJRu3x/lZ5tPsJHoK76Zr+QD0A9cH5gZR1XhDPE+ECnI1S2dAz3sgnHo5fNkPYyaTDhjZwkuq6bzn1xOqXfc7MdwW6xxOxKsmND+vOu5CK2Ypuu5GswUb5fkYnxnnWh7sK8BswykYdGhEFIuCCMkLztlpjo67rt4f73Gt41xAh93VuGQ7lpR/Z3zaqSin76kYSvbsL77ibXGZzb3zTb7l4Rj1Pq++oGNA==
    AWS_SECRET_ACCESS_KEY: AgCzoyVRmgg1Tie8+PakqcTB8MfRDM3BGDAfpRoNpeRUy1movP8PsUmRVHG7XIdDgsITlKOmqpJZvnubSAHnGUISy8+G42PehVtr7QNwFn10z4yxc96W4MC4a1qEvWXokVo7Jy5BhTEsKX4iF6Ga1CIdQ0lzRnZDRbi1L0Ggp694+9vD7lDBmrRfiqoh0vB1JyrsjDNCISgFVI+4XBdgNxjOgm5XONpIcnbPzUO1eL82MlZ/aTbrngnosTIW1T/zBoU3JYtXDi0Anz4aCj47WENZzGYnmz4XiuU8t6LZZiNOuUPrdOxqqw00b6I6YmB2tBksKFsnL9TUHAQC8tmU4xazDbxsE3lAD1uFwteAqfMSl0uzWXNB6bTOMJDp36nx6EAU1VgSY3xPyW8LkyrvfI/o1BnPI4wAiBeAcY4qXKLP4lxiEK+04+5HSAL8YxyhJ4cVx/wWLlIFp/Yon+8JhZ1f1Ozb/sMc8gulIzXvyr9vweVpRXCb9Anp1XVkw1SaxmkI6sevsH9GF91n+cmkZ05AKYSGJV/tKuAHdZHXZTEwSvcfRg2y+Rhs9q3w/kZj/S4pnhF1dX9GgzWF1994O5dHNwRadJXIDdedjv6E42NUEd2bcqKp+vj5nK5q2Qff/HW8xrCnQiHKE54DnIMt7Sj47otG4EiipJsK4WozKuZAFFmk0SU0YbjdW6LevJxN8qY1f6C5ZcbvJwdKWQWUE9Lp/tABxXHShW0NU+nYjBd3bZwtU9SbskGj
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        environment: demo
        folder: dns-infra
        subFolder: external-dns-aws
      name: aws-dns-creds
      namespace: dns-infra
    type: Opaque

