apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
  name: aws-dns-creds
  namespace: dns-infra
spec:
  encryptedData:
    AWS_ACCESS_KEY: AgC3LcFDGy9wCmT4cXB92eWo/tqQKFg4kjAEGYeK52IAiD2lq0k/lgB5JeisbQ+9DmnwGcnsLmONGtKyz7YWFRGFlwVSQ1i5YsAcdUQnXd5n8zV1d/QfKXxWeJPUmsn1NRQXRFnJeP1t8vG/GUxB5L1gXsRwFKvST8PKFDB4Se+QINDJI8flZ5n1uU4tte42P0z7x/PT3cXAxFgYV+pTIiZ93zodyBsYjsY4niFiTais21VhANryBrGd53KshpwLZ30nfdlMK+JN0WgkIT9goNuGtAWZJSXYFlt/6752txEwYqInYgu3NkB6PvQsj4S8ePZCrKkG2EHBpY7b2wAcdLPyKCByTTXLQN6DcLbkfgo4rYS/E1+qkcezlior+iheSdviRvFzCeyaMUzjfAjhTd0BUMoPZZ34mZsAwu6Qc9zLXPdJ5JsdPLnx+OxHC68qaUzgdK+oBkUOIfku3/vM8HzoOt2GNik6PxSGklzq14IpEfYdWrUV8NoFBgP57oEoLGLhAkinRmcXmeuGVJkR7ux2VvomhtBTh1Z0LZ1X/W6YApCz6SFfPiAEBYcak0WCEp1kkzbjmlB0XzQ75Jo8a1cMrXmzsn4LRvw8/lAwNU6CpBLrfbWHRlQe6Nvw53U595ONCoHZpH2dwla60AhDzsauz2YG2lCrcgNBRtP8A4EJkPC030VFnq79jLI/18bD7QLRNKk3bgV1drAakbS8ENnkDmtGRQ==
    AWS_SECRET_ACCESS_KEY: AgBbkAajEaJgc4rd9qcR/rtB6q39WBagYQ4oJiDYBtYYZGkDJQcMOeGRa/bQJHg8BnZM5SsfSTG0avD9SBoejjsW20SaXVZu+pqQzXQeCg+aKD6PeM8BdwZjrdKqrgSyTaUtVvV8UJhBOv6cG8SBbnvAK+r2foGmrYQ63ODaaS9S4c/zoiLgSmw0ISAWRYtsOT5UQWF4jC45PzuXXvOaUlfu2eTHYgy7HFdKBz9dxSEBSTn+5fXzhcnuCw3bm+PfGGKfbTLgkcMittP6xpY7Cc5ESv+XinpMbKOiTthOBKRbfjekOkTJWpQkpGLLyz600m2eBvONI2SKApVrPFGSl0C24/+/ltS1fVEM3E1RQ/b4lbr0j1Jgs8UeboqIqCZgbBmSz2H+rjA/790IFiy/X9MJAjp0pbq+KqWf6fG17Z4QFkCCkAgr32z7BWsGBQG0c/+An4DwkOhBNLvlznRk5y7qhi21Arl6uM6X6ZIvrljzYyESHM5dArPX9IuFli8Bsh4NlguqSJuUHeQtKBbvR0UNyEX6Ny096F+5jM0I95PnrXQrqDia+0WtyHW8fA+P/SJYJTB0iEFrGS9x3mztAd+XgBYagDbsSK3hDjFZJRNh0f4uBw6slZZpA+37ajSszCWzcc0HmxMff/3cGct/VFD+HnbeACVI/tTzbQk3OffEWdTsbXAAdAMM97VJVJJ9s03fCpK6GWCeCDj3qfAOd95613OgqHKSaW9gNK5W/CyHNazFNwFVPKzU
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-dns-creds
      namespace: dns-infra
    type: Opaque