helmCharts:
- name: vault
  namespace: security
  version: 0.18.0
  repo: https://helm.releases.hashicorp.com
  releaseName: vault
  includeCRDs: true
  valuesInline: 
    server:
      dev:
        enabled: true
        devRootToken: "bradmccoy"
      ingress:
        enabled: true
        labels:
          traffic: external
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-demo-aws
        ingressClassName: ""
        pathType: Prefix
        hosts:
          - host: vault.bradmccoy.io
            paths: []
        extraPaths: []
        tls:
          - secretName: vault-tls-certificate
            hosts:
              - vault.bradmccoy.io
