apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mono-repo
  namespace: ci-cd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/bradmccoy/bradmccoy.git
          revision: svc_cat
          directories:
          - path: chart/*
          - path: chart/bradmccoydev-console
            exclude: true
      - list:
          elements:
          - cluster: demo
            url: https://20.40.125.65
            values:
              CLIENT_ENVIRONMENT: demo             
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: bradmccoy
      source:
        repoURL: https://github.com/bradmccoydev/argo-demo.git
        targetRevision: svc_cat
        path: '{{path}}'
        helm:
          valueFiles:
            # - 'common-{{path.basename}}-values.yaml'
            - 'values.yaml'
      destination:
        server: https://20.40.125.65
        namespace: '{{path.basename}}'
      syncPolicy:
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
            prune: true 
            selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
        syncOptions:     # Sync options which modifies sync behavior
        - CreateNamespace=true     
