apiVersion: v2
name: external-dns-aws
namespace: dns-infra
description: external-dns-aws Helm chart for Kubernetes
type: application
version: 5.5.0
appVersion: "0.10.1"

dependencies:
- name: external-dns
  chart: bitnami/external-dns
  version: 5.5.0
  repository: https://charts.bitnami.com/bitnami
  values:
    - ../demo-external-dns-values.yaml
