apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: v1
kind: Namespace
metadata:
  name: direktiv-services-direktiv
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: direktiv
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  annotations:
    linkerd.io/inject: enabled
---
