apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data: 
  url: https://argocd.bradmccoy.io
  kustomize.buildOptions: --enable-helm
  repositories: |
      - url: https://github.com/bradmccoydev/argo-demo.git
  dex.config: |
      connectors:
      - type: microsoft
        id: microsoft
        name: KCD Guatemala
        config:
          clientID: cdc33587-12c3-4fc3-a163-33013a8af1ba
          clientSecret: $MICROSOFT_CLIENT_SECRET
          redirectURI: https://argocd.bradmccoy.io/api/dex/callback
          tenant: 1543c9b8-a1d1-4f26-bffb-1368aaeb582e
          groups:
            - moula.cloudengineering
         