helmCharts:
- name: linkerd2
  namespace: linkerd
  version: 2.11.1
  repo: https://helm.linkerd.io/stable
  releaseName: linkerd2
  includeCRDs: true
  valuesInline:
    linkerd2:
      installNamespace: false
      namespace: service-mesh
      controlPlaneTracing: true
      controlPlaneTracingNamespace: observability
      controllerLogLevel: debug
      identityTrustAnchorsPEM: |
        -----BEGIN CERTIFICATE-----
        MHcCAQEEIKKd6G1QvkXrHweaNY0Okl268HeKUMHo+KX2mClLmWlXoAoGCCqGSM49
        AwEHoUQDQgAE3JMktSh2l/JlYQFvpUpp75l/mBpvHGlP/ivLz8L9CR6dU46CRFtW
        2Ek4FBmORD8D3loDceIBK8pgQaJ2kKTCrA==
        -----END CERTIFICATE-----
      identity:
        issuer:
          tls:
            keyPEM: |
              -----BEGIN CERTIFICATE-----
              MIIBjTCCATOgAwIBAgIQFKEhG4tAOGSinAi/ub3MOzAKBggqhkjOPQQDAjAlMSMw
              IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMTEyMTUwMzU4
              NTFaFw0yNjEyMTQwMzU4NTFaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
              dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE3JMktSh2l/JlYQFv
              pUpp75l/mBpvHGlP/ivLz8L9CR6dU46CRFtW2Ek4FBmORD8D3loDceIBK8pgQaJ2
              kKTCrKNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
              VR0OBBYEFK8aOMatbsY5mYeXQLqze8FYS04aMAoGCCqGSM49BAMCA0gAMEUCIAlT
              NwRoIQe4GEAXGTWLI763Gw08MD1NMj+qoaawOVHyAiEApIpnqMsa5rqxsQa7OgPo
              orwA9AKAt7AaYvl0z+5F7Ds=
              -----END CERTIFICATE-----
            crtPEM: |
              -----BEGIN CERTIFICATE-----
              MHcCAQEEIKKd6G1QvkXrHweaNY0Okl268HeKUMHo+KX2mClLmWlXoAoGCCqGSM49
              AwEHoUQDQgAE3JMktSh2l/JlYQFvpUpp75l/mBpvHGlP/ivLz8L9CR6dU46CRFtW
              2Ek4FBmORD8D3loDceIBK8pgQaJ2kKTCrA==
              -----END CERTIFICATE-----
            crtExpiry: "2022-12-16T12:56:16Z"             
          scheme: kubernetes.io/tls
      proxyInjector:
        externalSecret: true
        caBundle: |
          -----BEGIN CERTIFICATE-----
          MIIBjTCCATOgAwIBAgIQFKEhG4tAOGSinAi/ub3MOzAKBggqhkjOPQQDAjAlMSMw
          IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMTEyMTUwMzU4
          NTFaFw0yNjEyMTQwMzU4NTFaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
          dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE3JMktSh2l/JlYQFv
          pUpp75l/mBpvHGlP/ivLz8L9CR6dU46CRFtW2Ek4FBmORD8D3loDceIBK8pgQaJ2
          kKTCrKNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
          VR0OBBYEFK8aOMatbsY5mYeXQLqze8FYS04aMAoGCCqGSM49BAMCA0gAMEUCIAlT
          NwRoIQe4GEAXGTWLI763Gw08MD1NMj+qoaawOVHyAiEApIpnqMsa5rqxsQa7OgPo
          orwA9AKAt7AaYvl0z+5F7Ds=
          -----END CERTIFICATE-----
      profileValidator:
        externalSecret: true
        caBundle: |
          -----BEGIN CERTIFICATE-----
          MIIBjTCCATOgAwIBAgIQFKEhG4tAOGSinAi/ub3MOzAKBggqhkjOPQQDAjAlMSMw
          IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMTEyMTUwMzU4
          NTFaFw0yNjEyMTQwMzU4NTFaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
          dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE3JMktSh2l/JlYQFv
          pUpp75l/mBpvHGlP/ivLz8L9CR6dU46CRFtW2Ek4FBmORD8D3loDceIBK8pgQaJ2
          kKTCrKNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
          VR0OBBYEFK8aOMatbsY5mYeXQLqze8FYS04aMAoGCCqGSM49BAMCA0gAMEUCIAlT
          NwRoIQe4GEAXGTWLI763Gw08MD1NMj+qoaawOVHyAiEApIpnqMsa5rqxsQa7OgPo
          orwA9AKAt7AaYvl0z+5F7Ds=
          -----END CERTIFICATE-----
      # This values.yaml file contains the values needed to enable HA mode.
      # Usage:
      #   helm install -f values.yaml -f values-ha.yaml
      enablePodAntiAffinity: true
      # proxy configuration
      proxy:
        resources:
          cpu:
            request: 100m
          memory:
            limit: 250Mi
            request: 20Mi
      # controller configuration
      controllerReplicas: 3
      controllerResources: &controller_resources
        cpu: &controller_resources_cpu
          limit: ""
          request: 100m
        memory:
          limit: 250Mi
          request: 50Mi
      destinationResources: *controller_resources
      publicAPIResources: *controller_resources
      # identity configuration
      identityResources:
        cpu: *controller_resources_cpu
        memory:
          limit: 250Mi
          request: 10Mi
      # heartbeat configuration
      heartbeatResources: *controller_resources
      # proxy injector configuration
      proxyInjectorResources: *controller_resources
      webhookFailurePolicy: Fail
      # service profile validator configuration
      spValidatorResources: *controller_resources

- name: linkerd-jaeger
  version: 2.11.1
  repo: https://helm.linkerd.io/stable
  releaseName: linkerd-jaeger
  includeCRDs: true
  valuesInline: 
    linkerd-jaeger:
      installNamespace: false
      namespace: linkerd-jaeger
      webhook:
        externalSecret: true
        caBundle: |
          -----BEGIN CERTIFICATE-----
          MIIBjTCCATOgAwIBAgIQFKEhG4tAOGSinAi/ub3MOzAKBggqhkjOPQQDAjAlMSMw
          IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMTEyMTUwMzU4
          NTFaFw0yNjEyMTQwMzU4NTFaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
          dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE3JMktSh2l/JlYQFv
          pUpp75l/mBpvHGlP/ivLz8L9CR6dU46CRFtW2Ek4FBmORD8D3loDceIBK8pgQaJ2
          kKTCrKNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
          VR0OBBYEFK8aOMatbsY5mYeXQLqze8FYS04aMAoGCCqGSM49BAMCA0gAMEUCIAlT
          NwRoIQe4GEAXGTWLI763Gw08MD1NMj+qoaawOVHyAiEApIpnqMsa5rqxsQa7OgPo
          orwA9AKAt7AaYvl0z+5F7Ds=
          -----END CERTIFICATE-----

- name: linkerd-viz
  version: 2.11.1
  repo: https://helm.linkerd.io/stable
  releaseName: linkerd-viz
  includeCRDs: true
  valuesInline: 
    linkerd-viz:
      installNamespace: false
      namespace: linkerd-viz
      linkerdNamespace: linkerd
      defaultLogLevel: debug
      tap:
        externalSecret: true
        caBundle: |
          -----BEGIN CERTIFICATE-----
          MIIBjTCCATOgAwIBAgIQFKEhG4tAOGSinAi/ub3MOzAKBggqhkjOPQQDAjAlMSMw
          IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMTEyMTUwMzU4
          NTFaFw0yNjEyMTQwMzU4NTFaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
          dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE3JMktSh2l/JlYQFv
          pUpp75l/mBpvHGlP/ivLz8L9CR6dU46CRFtW2Ek4FBmORD8D3loDceIBK8pgQaJ2
          kKTCrKNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
          VR0OBBYEFK8aOMatbsY5mYeXQLqze8FYS04aMAoGCCqGSM49BAMCA0gAMEUCIAlT
          NwRoIQe4GEAXGTWLI763Gw08MD1NMj+qoaawOVHyAiEApIpnqMsa5rqxsQa7OgPo
          orwA9AKAt7AaYvl0z+5F7Ds=
          -----END CERTIFICATE-----
      tapInjector:
        externalSecret: true
        caBundle: |
          -----BEGIN CERTIFICATE-----
          MIIBjTCCATOgAwIBAgIQFKEhG4tAOGSinAi/ub3MOzAKBggqhkjOPQQDAjAlMSMw
          IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMTEyMTUwMzU4
          NTFaFw0yNjEyMTQwMzU4NTFaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
          dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE3JMktSh2l/JlYQFv
          pUpp75l/mBpvHGlP/ivLz8L9CR6dU46CRFtW2Ek4FBmORD8D3loDceIBK8pgQaJ2
          kKTCrKNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
          VR0OBBYEFK8aOMatbsY5mYeXQLqze8FYS04aMAoGCCqGSM49BAMCA0gAMEUCIAlT
          NwRoIQe4GEAXGTWLI763Gw08MD1NMj+qoaawOVHyAiEApIpnqMsa5rqxsQa7OgPo
          orwA9AKAt7AaYvl0z+5F7Ds=
          -----END CERTIFICATE----- 
