apiVersion: v2
name: argo-cd
namespace: ci-cd
description: argo-cd Helm chart for Kubernetes
type: application
version: 3.26.11
appVersion: "v2.1.7"

dependencies:
- name: argo-cd
  chart: argo/argo-cd
  version: 3.26.11
  condition: argo-cd.enabled
  repository: https://argoproj.github.io/argo-helm
