server:

  service:
    type: NodePort

  extraArgs:
  - --insecure

  ingress: 
    enabled: true
    https: false
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-demo-aws
    hosts:
      - argocd.bradmccoy.io
    tls:
      - hosts:
          - argocd.bradmccoy.io
        secretName: letsencrypt-demo-aws

  additionalProjects:
  - name: kcd-guatemala
    namespace: ci-cd
    description: KCD Guatemala Project
    sourceRepos:
    - '*'
    destinations:
    - namespace: '*'
      server: 
    clusterResourceWhitelist: 
    - group: '*'
      kind: '*'
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  rbacConfig:
    policy.default: role:readonly
    policy.csv: |
      g, brad@odysseycloud.io, role:admin
      g, amit@odysseycloud.io, role:admin
    scopes: '[email,group]'

  config:
    url: https://argocd.bradmccoy.io
    kustomize.buildOptions: --enable-helm
    repositories: |
      - url: https://github.com/bradmccoydev/argo-demo.git
    dex.config: | 
      connectors:
      - type: saml
        id: saml
        name: saml
        config:
          ssoURL: https://accounts.google.com/o/saml2?idpid=C02ihwbf4
          entityIssuer: https://argocd.bradmccoy.io/api/dex/callback
          caData: |
            TUlJRGREQ0NBbHlnQXdJQkFnSUdBWGZ0dEpFRE1BMEdDU3FHU0liM0RRRUJDd1VBTUhzeEZEQVNCZ05WQkFvVEMwZHZiMmRzWlNCSgpibU11TVJZd0ZBWURWUVFIRXcxTmIzVnVkR0ZwYmlCV2FXVjNNUTh3RFFZRFZRUURFd1pIYjI5bmJHVXhHREFXQmdOVkJBc1REMGR2CmIyZHNaU0JHYjNJZ1YyOXlhekVMTUFrR0ExVUVCaE1DVlZNeEV6QVJCZ05WQkFnVENrTmhiR2xtYjNKdWFXRXdIaGNOTWpFd016QXgKTVRJeE1qUTNXaGNOTWpZd01qSTRNVEl4TWpRM1dqQjdNUlF3RWdZRFZRUUtFd3RIYjI5bmJHVWdTVzVqTGpFV01CUUdBMVVFQnhNTgpUVzkxYm5SaGFXNGdWbWxsZHpFUE1BMEdBMVVFQXhNR1IyOXZaMnhsTVJnd0ZnWURWUVFMRXc5SGIyOW5iR1VnUm05eUlGZHZjbXN4CkN6QUpCZ05WQkFZVEFsVlRNUk13RVFZRFZRUUlFd3BEWVd4cFptOXlibWxoTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEEKTUlJQkNnS0NBUUVBNit6NkxvUVc3RW5abzF2N2NLODBEelNmK0Yzc1FjcXJwTmlyMGNINU5yS2RmelJTNEV4UzBQa1QxbWlia3d0MgpnRklSOEF5bUhjbDVhTS9qQzYyT3QwV25jV0UySnBhdWtnbVREWThLLytDQkFzc2Z2MFZnZEczaG5YcnplNjlOY2FiVUtkSTBoTUp6Cng1WFBuUmFXRGw1TEdRQlRpTkl4QkgydXlCeFBObjQ4V1hHN3lWejg1WXFnbGU3d3dmcFpkV001WC9Xang3TlNhWHgrRXVva2h5eTIKN3pEdlprcFZrc2pMZkIxY2J5VFBKUUdkci9hRzkxbGErTXVMZFJHcnZlL0JWRjNKVmtwOGVhYWxqSUJOUWwyYm5VK2UwV0ZhM3hVYQo1cCtrNmt5RnZjTGwrTHc5RExPTFNFVW1TVFVvOExkeGhXNW1ZYVd5N0Zlb1gwNERzd0lEQVFBQk1BMEdDU3FHU0liM0RRRUJDd1VBCkE0SUJBUUI5VWpvaGY2c0hTZTdUb2RMNisvOVl4SE1ib2EvSWg2dUpKdkRaZGR0Nlo0TmNtMGorNlZwd2I5L1JaKzFwT1l0eTJDOTQKSlMrcnZwTFYxVXRZdWR0VVE1YW5XUkhqamFsTXNkb3RsTWxQeVJpSVFhWXUyV2RNZ3Z0Q1AzcHNWbjEveVIyTkw5MnJFUzJ3OENuSQp2L0tYcmozZTJrSG9zeWdkUEtFdTkzSnhuZEFVWVJUNVJQOFdWbFQ4L1JMbS91Z1Q2UWttUDc2elIyQUNRRUtZZFk4aWtPNmk3REQrCmFxWTBadDdqNkNNWmtHRlpaUXlBYXgwN3NPN3RqOFZBdThwYnowRjFQU1dLbmlmZ1JGRW1XV2FLdmF0NFBOdFhsajEzdGlPTFNobWoKekMxVjE5YVc0WU5oVE90d1BmbHFQYW9RYUdaNTY5THVidFJZeVIzOU9NVDI=
          redirectURI: https://argocd.bradmccoy.io/api/dex/callback
          usernameAttr: name
          emailAttr: email
          # optional
          ssoIssuer: https://accounts.google.com/o/saml2?idpid=C02ihwbf4
