repositories:
  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io

values:
  - sealed-secrets:
      enabled: true
  - external-dns:
      enabled: true
  - cert-manager:
      enabled: true
      
environments:
  demo:
    values:
      - sealed-secrets:
          enabled: true
      - external-dns:
          enabled: true
      - cert-manager:
          enabled: true

releases:
  - name: sealed-secrets-controller
    namespace: security
    chart: sealed-secrets/sealed-secrets 
    version: 1.16.1
    condition: sealed-secrets.enabled

  - name: external-dns
    namespace: dns-infra
    chart: bitnami/external-dns
    version: 5.6.0
    condition: external-dns.enabled
    values:
      - ../kube-infra/helm/dns-infra/external-dns-aws/common-external-dns-values.yaml
      - ../kube-infra/helm/dns-infra/external-dns-aws/{{ requiredEnv "CLIENT_ENVIRONMENT" }}-external-dns-values.yaml

  - name: cert-manager
    namespace: dns-infra
    chart: jetstack/cert-manager
    version: 1.6.1
    condition: cert-manager.enabled
    values:
      - ../kube-infra/helm/dns-infra/cert-manager/{{ requiredEnv "CLIENT_ENVIRONMENT" }}-cert-manager-values.yaml
