repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

values:
  - external-dns:
      enabled: true
  - cert-manager:
      enabled: true
  - ingress-nginx:
      enabled: true
      
environments:
  demo:
    values:
      - external-dns:
          enabled: true
      - cert-manager:
          enabled: true
      - ingress-nginx:
          enabled: true

releases:
  - name: external-dns
    namespace: dns-infra
    chart: bitnami/external-dns
    version: 5.5.0
    condition: external-dns.enabled
    values:
      - ../kube-infra/helm/dns-infra/external-dns-aws/common-external-dns-values.yaml
      - ../kube-infra/helm/dns-infra/external-dns-aws/{{ requiredEnv "CLIENT_ENVIRONMENT" }}-external-dns-values.yaml

  - name: cert-manager
    namespace: dns-infra
    chart: jetstack/cert-manager
    version: 1.6.1
    condition: cert-manager.enabled
    values:
      - ../kube-infra/helm/dns-infra/cert-manager/demo-cert-manager-values.yaml

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.0.10
    condition: ingress-nginx.enabled
    values:
      - ../kube-infra/helm/dns-infra/ingress-nginx/{{ requiredEnv "CLIENT_ENVIRONMENT" }}-ingress-nginx-values.yaml
