apiVersion: v2
name: knative
namespace: knative-serving
description: knative Helm chart for Kubernetes
type: application
version: 0.5.10
appVersion: "0.5.10"

dependencies:
- name: knative
  chart: direktiv/knative
  version: 0.5.10
  repository: https://charts.direktiv.io
  values:
    - ../demo-knative-values.yaml
